from fastapi import FastAPI, File, UploadFile, Request, Response
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
import uvicorn
import markdown
from xhtml2pdf import pisa
from typing import List
import io

# importing custom logic

from logic import NotesDigitizer 

app = FastAPI()
templates = Jinja2Templates(directory="templates")

print("Initializing logic...")
digitizer = NotesDigitizer()

# help funcs

class PDFRequest(BaseModel):
    notes: str

def convert_markdown_to_pdf(markdown_text):
    html_body = markdown.markdown(markdown_text)
    full_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 12pt; }}
            h1 {{ color: #4f46e5; border-bottom: 2px solid #ddd; }}
            code {{ background-color: #f3f4f6; padding: 2px; }}
            pre {{ background-color: #f1f5f9; padding: 10px; border-radius: 5px; }}
            ul {{ line-height: 1.6; }}
        </style>
    </head>
    <body>
        <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="border:none;">Lecturify Notes</h1>
            <p style="color: #666; font-size: 10pt;">Generated by AI</p>
        </div>
        {html_body}
    </body>
    </html>
    """
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(full_html, dest=pdf_buffer)
    if pisa_status.err:
        return None
    return pdf_buffer.getvalue()

# ~~~ API Endpoints ~~~

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/digitize-batch")
async def digitize_batch(files: List[UploadFile] = File(...)):
    file_bytes_list = []
    for file in files:
        content = await file.read()
        file_bytes_list.append(content)

    result_markdown = digitizer.process_batch(file_bytes_list)
    return {"notes": result_markdown}

@app.post("/generate-pdf")
async def generate_pdf(req: PDFRequest):
    pdf_bytes = convert_markdown_to_pdf(req.notes)
    if not pdf_bytes:
        return {"error": "PDF generation failed"}

    return Response(content=pdf_bytes, media_type="application/pdf")

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)